### DISCUSSION TITLE
How to specify a Changie version

### DISCUSSION THREAD

**Discussion by llaville** [miniscruff/changie-action#25] [Q&A] [answered]
When I read code of [action.yaml](https://github.com/miniscruff/changie-action/blob/v0.2.0/action.yml#L9-L12) I though we could change Changie version. 

```
                name: Build Release Notes
                uses: miniscruff/changie-action@v0
                with:
                    version: 1.10.0
                    args: merge
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Here is my try : https://github.com/llaville/php-compatinfo-db/actions/runs/3450425595/jobs/5759010078#step:6:3

Is it the right syntax, or did I misunderstood something ?
