### DISCUSSION TITLE
How to specify options with command on `args` settings

### DISCUSSION THREAD

**Discussion by llaville** [miniscruff/changie-action#26] [Q&A] [answered]
I want to specify options with the `batch` command, but it does not work with two following syntaxt, I've tried

```
                uses: miniscruff/changie-action@v0
                with:
                    version: v1.10.0
                    args: batch --keep --prerelease snapshot

```
or 
```
                uses: miniscruff/changie-action@v0
                with:
                    version: v1.10.0
                    args: 'batch --keep --prerelease snapshot'

```

See my workflow run results at https://github.com/llaville/docker-php-toolbox/actions/runs/3468787760/jobs/5795054670

PS: And even with double quote
or 
```
                uses: miniscruff/changie-action@v0
                with:
                    version: v1.10.0
                    args: "batch --keep --prerelease snapshot"

```
