### ISSUE TITLE
Support running changie in a custom directory

### ISSUE THREAD

**Issue by wjam** [miniscruff/changie-action#209]
It would be useful to be able to run changie within custom directories, such as if `actions/checkout` was run with `path` specified.

**Comment by miniscruff** [comment]
I am curious as to your layout for this, are you using a mono repo? But either way it seems like a fair request.

**Comment by wjam** [comment]
It's more inter-repository. Releasing a thing in one repository causes a workflow to raise a PR against _another_ repository with the new version (which uses changie to manage its release notes)

**Comment by Blacksmoke16** [comment]
Bump, this would come in handy for me as well. Or alternatively it could be nice if the action worked more like other actions being like `setup-changie` and just exposes the binary on path and lets you do whatever. Then you could just leverage `working-directory` with the `run` option and not have to deal with it internally.

**Comment by miniscruff** [comment]
> Bump, this would come in handy for me as well. Or alternatively it could be nice if the action worked more like other actions being like `setup-changie` and just exposes the binary on path and lets you do whatever. Then you could just leverage `working-directory` with the `run` option and not have to deal with it internally.

I definitely think there is room here for those features. I just myself have not needed them and definitely forgot about this issue as this project has just been very stable since the node 20 update. I would be happy to try and give this a try but would also accept PRs.

**Comment by Blacksmoke16** [comment]
As it turned out for my use case all I needed to do is:
```yaml
  - name: Setup Changie
    env:
      CHANGIE_VERSION: 1.22.1
    run: |
      wget https://github.com/miniscruff/changie/releases/download/v${{ env.CHANGIE_VERSION }}/changie_${{ env.CHANGIE_VERSION }}_linux_amd64.deb --quiet -O changie.deb
      sudo dpkg -i changie.deb
```
So just documenting this might be sufficient than refactoring the whole action.
